"""Cognitive IR — canonical form for cross-executor analysis.

This module defines the **emergent** canonical form of every cognitive
computation.  Nothing enters this module until at least 3 independent
executors emit the corresponding transition family.

Current IR vocabulary (data-driven from Transition Observatory)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    eligible families (≥3 executors)::

        commit_outcome          ✓  classification + diagnosis + evaluation

    ineligible families (<3 executors)::

        decision_condition      —  classification only
        probabilistic_inference —  diagnosis only
        scoring                 —  evaluation only
        phase_transition        —  diagnosis + evaluation (2)
        structural_navigate     —  classification only

Design principle
━━━━━━━━━━━━━━
No canonical form is defined until the evidence demands it.
The ``CognitiveCommit`` dataclass is deliberately minimal —
it represents only what all three executors share: an outcome
label and its supporting context.  When an executor class arrives
with *new* transition actions, the IR is revised.

Reference
━━━━━━━━━
The Transition Observatory report is generated by::

    python tools/transition_observatory.py
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class CognitiveCommit:
    """The universal shape of a cognitive outcome.

    Every executor terminates by committing to one outcome.
    ``label`` is the committed value (a string).  ``meta``
    holds executor-specific context (confidence, posteriors,
    path, etc.).
    """

    label: str
    confidence: float = 0.0
    meta: dict[str, Any] = field(default_factory=dict)

    def __bool__(self) -> bool:
        return bool(self.label)


def commit_from_executor_result(result: dict[str, Any] | None) -> CognitiveCommit | None:
    """Build a ``CognitiveCommit`` from an executor's ``result()`` dict.

    All three concrete executors produce result dicts with at least
    one label field (``result``, ``primary_diagnosis``, ``judgment``)
    and optionally a ``confidence`` number.  This function normalises
    them into the canonical envelope.
    """
    if result is None:
        return None

    raw = result.get("result")

    if isinstance(raw, dict):
        label = raw.get("primary_diagnosis") or raw.get("label")
    elif isinstance(raw, str):
        label = raw
    else:
        label = None

    if label is None:
        label = result.get("map_hypothesis") or result.get("judgment") or result.get("label")
    if label is None:
        solved = result.get("solved")
        if solved is True:
            label = "solved"
        elif solved is False:
            return None
    if label is None:
        return None

    confidence = float(
        result.get("map_probability")
        or (isinstance(raw, dict) and raw.get("confidence", 0.0))
        or result.get("confidence", 0.0)
    )

    return CognitiveCommit(
        label=str(label),
        confidence=confidence,
        meta={
            k: v
            for k, v in result.items()
            if k not in ("result", "judgment", "confidence", "map_hypothesis", "map_probability", "solved")
        },
    )
